language: cpp
compiler: gcc
dist: focal

addons:
  apt:
    packages:
      - devscripts
      - equivs
      - gcovr
      - lcov
    update: true

before_install:
  - sudo mk-build-deps -i

script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=coverage
  - make -j$(nproc)
  - make test
  - make coverage
after_success:
  - cd build
  - bash <(curl -s https://codecov.io/bash)
